name = "Crazyflie"
uuid = "69416ee2-9ea2-11e9-0a75-cfadc9107a51"
authors = ["Arun Lakshmanan <lakshma2@illinois.edu>"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
CoordinateTransformations = "0.5"
GeometryTypes = "0.7"
MeshCat = "0.7"
PyCall = "1.91"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
