name = "Crazyflie"
uuid = "69416ee2-9ea2-11e9-0a75-cfadc9107a51"
authors = ["Arun Lakshmanan <lakshma2@illinois.edu>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.91"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
